# ============================================================
# Microbe-ARG Correlation Plot
# ============================================================
#
# Required input file 1: microbial taxon abundance table
# ------------------------------------------------------------
# Default file name:
#   all.marker_rpm.genus.long.tsv
#
# This table should be generated by the marker abundance workflow.
# It must be a tab-delimited TSV file with a header.
#
# Required columns:
#   sample_id            Sample ID. Must match sample_id in the ARG table.
#   marker               Marker type, for example 16S, ITS, 18S.
#   domain               Microbial domain or group, for example Bacteria, Archaea, Fungi.
#   rank                 Taxonomic rank, for example phylum, class, order, family, genus, species.
#   lineage              Full lineage string. This is used as the unique taxon identifier.
#   taxon_marker_reads   Marker read count assigned to this taxon.
#   clean_reads_total    Total clean reads used for RPM normalization.
#   marker_rpm           Marker abundance normalized as RPM.
#
# Optional columns:
#   year
#   month
#   depth
#   site_id
#   site_type
#   group
#   any other metadata columns
#
# Example:
#   sample_id        year  month  depth  marker  domain    rank   lineage                                      taxon_marker_reads  clean_reads_total  marker_rpm
#   201704_MF1_0002 2017  4      0-2    16S     Archaea   genus  d__Archaea;p__Asgardarchaeota;g__Lokiarchaeia 248                 700345214          0.3541
#   201704_MF1_0002 2017  4      0-2    ITS     Fungi     genus  k__Fungi;p__Ascomycota;g__Trichophyton        10                  700345214          0.0143
#
#
# Required input file 2: ARG abundance table
# ------------------------------------------------------------
# Default file name:
#   arg_abundance.tsv
#
# Two formats are supported.
#
# Format A: long format
# ---------------------
# Required columns:
#   sample_id        Sample ID. Must match sample_id in the microbial abundance table.
#   arg_group        ARG group, ARG class, ARG subtype, or Total_ARG.
#   arg_abundance    ARG abundance value, for example RPM, TPM, RPKM, or relative abundance.
#
# Example:
#   sample_id        arg_group   arg_abundance
#   201704_MF1_0002 Total_ARG   0.00012
#   201704_MF1_0002 sul         0.00002
#   201704_MF1_0002 bla         0.00001
#
#
# Format B: wide format
# ---------------------
# Required column:
#   sample_id
#
# Other numeric columns are treated as ARG abundance columns.
#
# Example:
#   sample_id        Total_ARG   sul       bla       tet
#   201704_MF1_0002 0.00012     0.00002   0.00001   0.00003
#   201704_MF1_0608 0.00035     0.00004   0.00002   0.00008
#
#
# Important notes
# ------------------------------------------------------------
# 1. sample_id must be shared by the microbial table and the ARG table.
# 2. marker_rpm is used as microbial taxon abundance.
# 3. arg_abundance is used as ARG abundance.
# 4. lineage is used as the unique taxon ID to avoid incorrect merging of
#    unresolved taxa such as Incertae_sedis.
# 5. For UNITE fungal data, SH-aware lineage labels are strongly recommended
#    when unresolved ranks are present.
# 6. The script performs correlation across samples.
# 7. By default, Spearman correlation and BH-adjusted q values are used.
#
# Main output files
# ------------------------------------------------------------
#   microbe_arg_correlation/taxa_ARG_correlation_genus.tsv
#   microbe_arg_correlation/microbe_ARG_correlation_genus.pdf
#   microbe_arg_correlation/microbe_ARG_correlation_genus.png
#
# ============================================================
# ============================================================
# Correlation between microbial taxa and ARG abundance
# Horizontal bubble plot for mangrove sediment samples
# Domains: Bacteria, Archaea, Fungi
# ============================================================

library(tidyverse)
library(data.table)
library(ggsci)
library(patchwork)
library(scales)

# ----------------------------
# 1. Parameters
# ----------------------------

taxa_file <- "all.marker_rpm.genus.long.tsv"
arg_file  <- "arg_abundance.tsv"

output_dir <- "microbe_arg_correlation"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

target_rank <- "genus"

domain_keep <- c("Bacteria", "Archaea", "Fungi")

cor_method <- "spearman"

q_method <- "BH"

q_cutoff_for_star <- 0.10

top_n_taxa_per_domain <- 25

min_detected_samples <- 5

min_samples_for_correlation <- 10

use_total_arg <- TRUE

arg_groups_to_plot <- NULL
# Example:
# arg_groups_to_plot <- c("Total_ARG")
# arg_groups_to_plot <- c("Total_ARG", "sul", "bla", "tet")

panel_a_orientation <- "horizontal"
# "horizontal": taxa on x-axis, ARG group on y-axis
# "vertical"  : taxa on y-axis, ARG group on x-axis

make_scatter_panels <- TRUE
n_scatter_pairs <- 2

pseudo_count <- 1e-8

# ----------------------------
# 2. Nature-like theme
# ----------------------------

theme_nature <- function(base_size = 8) {
  theme_classic(base_size = base_size) +
    theme(
      text = element_text(color = "black"),
      axis.text = element_text(color = "black"),
      axis.title = element_text(color = "black"),
      axis.line = element_line(linewidth = 0.35, color = "black"),
      axis.ticks = element_line(linewidth = 0.35, color = "black"),
      strip.background = element_blank(),
      strip.text = element_text(face = "bold", size = base_size + 1),
      legend.title = element_text(size = base_size),
      legend.text = element_text(size = base_size - 1),
      legend.key.size = unit(0.35, "cm"),
      plot.title = element_text(face = "bold", size = base_size + 2),
      plot.margin = margin(4, 4, 4, 4)
    )
}

# ----------------------------
# 3. Helper functions
# ----------------------------

rank_prefix <- c(
  domain = "d__",
  phylum = "p__",
  class = "c__",
  order = "o__",
  family = "f__",
  genus = "g__",
  species = "s__"
)

extract_rank_label <- function(lineage, rank) {
  prefix <- rank_prefix[[rank]]
  
  if (is.null(prefix)) {
    return(lineage)
  }
  
  parts <- stringr::str_split(lineage, ";", simplify = FALSE)[[1]]
  hit <- parts[stringr::str_starts(parts, fixed(prefix))]
  
  if (length(hit) == 0) {
    out <- tail(parts, 1)
  } else {
    out <- hit[1]
  }
  
  out <- stringr::str_remove(out, paste0("^", prefix))
  out <- stringr::str_replace_all(out, "_", " ")
  out
}

make_unique_plot_labels <- function(df) {
  df %>%
    group_by(domain, taxon_label) %>%
    mutate(
      label_n = n(),
      sh_id = stringr::str_extract(lineage, "SH[0-9]+\\.[A-Za-z0-9]+"),
      taxon_plot_label = case_when(
        label_n == 1 ~ taxon_label,
        !is.na(sh_id) ~ paste0(taxon_label, " | ", sh_id),
        TRUE ~ paste0(taxon_label, " | ", row_number())
      )
    ) %>%
    ungroup() %>%
    select(-label_n, -sh_id)
}

read_arg_table <- function(arg_file, use_total_arg = TRUE) {
  arg_raw <- data.table::fread(
    arg_file,
    sep = "\t",
    header = TRUE,
    data.table = FALSE,
    check.names = FALSE
  )
  
  names(arg_raw) <- trimws(names(arg_raw))
  
  if (!"sample_id" %in% names(arg_raw)) {
    stop("ARG table must contain sample_id column.")
  }
  
  long_group_candidates <- c("arg_group", "arg_class", "arg_type", "ARG", "arg")
  long_value_candidates <- c("arg_abundance", "arg_rpm", "rpm", "abundance", "value")
  
  group_col <- intersect(long_group_candidates, names(arg_raw))[1]
  value_col <- intersect(long_value_candidates, names(arg_raw))[1]
  
  if (!is.na(group_col) && !is.na(value_col)) {
    arg_long <- arg_raw %>%
      transmute(
        sample_id = as.character(sample_id),
        arg_group = as.character(.data[[group_col]]),
        arg_abundance = as.numeric(.data[[value_col]])
      )
  } else {
    meta_exclude <- c(
      "sample_id", "year", "month", "depth",
      "site_id", "site_type", "group", "clean_reads_total"
    )
    
    numeric_cols <- names(arg_raw)[sapply(arg_raw, is.numeric)]
    arg_metric_cols <- setdiff(numeric_cols, meta_exclude)
    
    if (length(arg_metric_cols) == 0) {
      stop(
        "ARG table must be either long format ",
        "(sample_id, arg_group, arg_abundance) or wide format with numeric ARG columns."
      )
    }
    
    arg_long <- arg_raw %>%
      mutate(sample_id = as.character(sample_id)) %>%
      select(sample_id, all_of(arg_metric_cols)) %>%
      pivot_longer(
        cols = all_of(arg_metric_cols),
        names_to = "arg_group",
        values_to = "arg_abundance"
      )
  }
  
  arg_long <- arg_long %>%
    filter(!is.na(arg_abundance)) %>%
    group_by(sample_id, arg_group) %>%
    summarise(arg_abundance = sum(arg_abundance, na.rm = TRUE), .groups = "drop")
  
  if (use_total_arg && !"Total_ARG" %in% unique(arg_long$arg_group)) {
    total_arg <- arg_long %>%
      group_by(sample_id) %>%
      summarise(
        arg_group = "Total_ARG",
        arg_abundance = sum(arg_abundance, na.rm = TRUE),
        .groups = "drop"
      )
    
    arg_long <- bind_rows(arg_long, total_arg)
  }
  
  arg_long
}

run_one_correlation <- function(x, y, method = "spearman") {
  ok <- is.finite(x) & is.finite(y)
  x <- x[ok]
  y <- y[ok]
  
  n_used <- length(x)
  
  if (n_used < min_samples_for_correlation) {
    return(tibble(correlation = NA_real_, p_value = NA_real_, n_used = n_used))
  }
  
  if (length(unique(x)) < 2 || length(unique(y)) < 2) {
    return(tibble(correlation = NA_real_, p_value = NA_real_, n_used = n_used))
  }
  
  ct <- suppressWarnings(cor.test(x, y, method = method, exact = FALSE))
  
  tibble(
    correlation = unname(ct$estimate),
    p_value = ct$p.value,
    n_used = n_used
  )
}

# ----------------------------
# 4. Read taxa table
# ----------------------------

taxa_raw <- data.table::fread(
  taxa_file,
  sep = "\t",
  header = TRUE,
  data.table = FALSE,
  check.names = FALSE
)

names(taxa_raw) <- trimws(names(taxa_raw))

required_taxa_cols <- c(
  "sample_id", "marker", "domain", "rank",
  "lineage", "taxon_marker_reads",
  "clean_reads_total", "marker_rpm"
)

missing_cols <- setdiff(required_taxa_cols, names(taxa_raw))

if (length(missing_cols) > 0) {
  stop("Missing required columns in taxa table: ", paste(missing_cols, collapse = ", "))
}

taxa_dat <- taxa_raw %>%
  mutate(
    sample_id = as.character(sample_id),
    domain = as.character(domain),
    rank = as.character(rank),
    lineage = as.character(lineage),
    marker_rpm = as.numeric(marker_rpm)
  ) %>%
  filter(
    rank == target_rank,
    domain %in% domain_keep,
    !is.na(marker_rpm),
    marker_rpm > 0
  ) %>%
  mutate(
    taxon_key = paste(domain, lineage, sep = "||"),
    taxon_label = map_chr(lineage, extract_rank_label, rank = target_rank)
  )

# ----------------------------
# 5. Read ARG abundance table
# ----------------------------

arg_long <- read_arg_table(arg_file, use_total_arg = use_total_arg)

if (!is.null(arg_groups_to_plot)) {
  arg_long <- arg_long %>%
    filter(arg_group %in% arg_groups_to_plot)
}

if (nrow(arg_long) == 0) {
  stop("No ARG records left after filtering arg_groups_to_plot.")
}

# ----------------------------
# 6. Select taxa for plotting and correlation
# ----------------------------

common_samples <- intersect(unique(taxa_dat$sample_id), unique(arg_long$sample_id))

if (length(common_samples) < min_samples_for_correlation) {
  stop("Too few common samples between taxa table and ARG table.")
}

taxa_dat <- taxa_dat %>%
  filter(sample_id %in% common_samples)

arg_long <- arg_long %>%
  filter(sample_id %in% common_samples)

all_samples <- sort(common_samples)

taxa_info <- taxa_dat %>%
  group_by(domain, lineage, taxon_key, taxon_label) %>%
  summarise(
    total_rpm = sum(marker_rpm, na.rm = TRUE),
    detected_samples = n_distinct(sample_id[marker_rpm > 0]),
    .groups = "drop"
  ) %>%
  filter(detected_samples >= min_detected_samples) %>%
  group_by(domain) %>%
  arrange(desc(total_rpm), .by_group = TRUE) %>%
  slice_head(n = top_n_taxa_per_domain) %>%
  ungroup() %>%
  make_unique_plot_labels()

selected_taxa <- taxa_info$taxon_key

if (length(selected_taxa) == 0) {
  stop("No taxa selected. Try reducing min_detected_samples or increasing top_n_taxa_per_domain.")
}

taxa_complete <- taxa_dat %>%
  filter(taxon_key %in% selected_taxa) %>%
  group_by(sample_id, taxon_key) %>%
  summarise(marker_rpm = sum(marker_rpm, na.rm = TRUE), .groups = "drop") %>%
  complete(
    sample_id = all_samples,
    taxon_key = selected_taxa,
    fill = list(marker_rpm = 0)
  )

taxa_mat <- taxa_complete %>%
  pivot_wider(
    names_from = taxon_key,
    values_from = marker_rpm,
    values_fill = 0
  ) %>%
  arrange(sample_id)

arg_mat <- arg_long %>%
  group_by(sample_id, arg_group) %>%
  summarise(arg_abundance = sum(arg_abundance, na.rm = TRUE), .groups = "drop") %>%
  complete(
    sample_id = all_samples,
    arg_group = unique(arg_long$arg_group),
    fill = list(arg_abundance = 0)
  ) %>%
  pivot_wider(
    names_from = arg_group,
    values_from = arg_abundance,
    values_fill = 0
  ) %>%
  arrange(sample_id)

taxa_mat <- taxa_mat %>% filter(sample_id %in% all_samples)
arg_mat <- arg_mat %>% filter(sample_id %in% all_samples)

arg_groups <- setdiff(names(arg_mat), "sample_id")

# ----------------------------
# 7. Correlation analysis
# ----------------------------

cor_results <- list()
idx <- 1

for (tk in selected_taxa) {
  for (ag in arg_groups) {
    x <- taxa_mat[[tk]]
    y <- arg_mat[[ag]]
    
    one <- run_one_correlation(x, y, method = cor_method) %>%
      mutate(
        taxon_key = tk,
        arg_group = ag
      )
    
    cor_results[[idx]] <- one
    idx <- idx + 1
  }
}

cor_df <- bind_rows(cor_results) %>%
  mutate(
    q_value = p.adjust(p_value, method = q_method)
  ) %>%
  left_join(taxa_info, by = "taxon_key") %>%
  mutate(
    q_value_safe = pmax(q_value, 1e-14, na.rm = TRUE),
    q_log10 = -log10(q_value_safe),
    sig_label = case_when(
      !is.na(q_value) & q_value < 0.001 ~ "***",
      !is.na(q_value) & q_value < 0.01 ~ "**",
      !is.na(q_value) & q_value < q_cutoff_for_star ~ "*",
      TRUE ~ ""
    )
  )

write_tsv(
  cor_df,
  file.path(output_dir, paste0("taxa_ARG_correlation_", target_rank, ".tsv"))
)

# ----------------------------
# 8. Ordering for panel A
# ----------------------------

taxon_order_df <- cor_df %>%
  group_by(domain, taxon_key, taxon_plot_label) %>%
  summarise(
    max_abs_r = max(abs(correlation), na.rm = TRUE),
    total_rpm = first(total_rpm),
    .groups = "drop"
  ) %>%
  arrange(domain, desc(max_abs_r), desc(total_rpm)) %>%
  mutate(taxon_plot_label = factor(taxon_plot_label, levels = unique(taxon_plot_label)))

cor_df <- cor_df %>%
  left_join(
    taxon_order_df %>% select(domain, taxon_key, taxon_plot_label_order = taxon_plot_label),
    by = c("domain", "taxon_key")
  ) %>%
  mutate(
    domain = factor(domain, levels = domain_keep),
    taxon_plot_label = factor(as.character(taxon_plot_label), levels = levels(taxon_order_df$taxon_plot_label)),
    arg_group = factor(arg_group, levels = arg_groups)
  )

# ----------------------------
# 9. Panel A: horizontal bubble correlation plot
# ----------------------------

if (panel_a_orientation == "horizontal") {
  p_a <- ggplot(
    cor_df,
    aes(
      x = taxon_plot_label,
      y = arg_group
    )
  ) +
    geom_point(
      aes(
        size = total_rpm,
        color = correlation,
        fill = q_log10
      ),
      shape = 21,
      stroke = 0.75,
      alpha = 0.95
    ) +
    geom_text(
      aes(label = sig_label),
      size = 2.4,
      color = "black"
    ) +
    facet_grid(domain ~ ., scales = "free_x", space = "free_x") +
    scale_color_gradient2(
      low = "#3B4CC0",
      mid = "grey90",
      high = "#B40426",
      midpoint = 0,
      limits = c(-1, 1),
      name = "Correlation"
    ) +
    scale_fill_gradient(
      low = "grey90",
      high = "black",
      name = "q value\n(-log10)"
    ) +
    scale_size_continuous(
      range = c(1.2, 6),
      trans = "log10",
      name = "Abundance\n(total RPM)"
    ) +
    labs(
      title = "Microbial taxa associated with ARG abundance in mangrove sediments",
      x = paste0(str_to_title(target_rank), " taxa"),
      y = "ARG group"
    ) +
    theme_nature(base_size = 8) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
      panel.spacing.x = unit(1.2, "lines"),
      legend.position = "bottom"
    )
} else {
  p_a <- ggplot(
    cor_df,
    aes(
      x = arg_group,
      y = taxon_plot_label
    )
  ) +
    geom_point(
      aes(
        size = total_rpm,
        color = correlation,
        fill = q_log10
      ),
      shape = 21,
      stroke = 0.75,
      alpha = 0.95
    ) +
    geom_text(
      aes(label = sig_label),
      size = 2.4,
      color = "black"
    ) +
    facet_grid(domain ~ ., scales = "free_y", space = "free_y") +
    scale_color_gradient2(
      low = "#3B4CC0",
      mid = "grey90",
      high = "#B40426",
      midpoint = 0,
      limits = c(-1, 1),
      name = "Correlation"
    ) +
    scale_fill_gradient(
      low = "grey90",
      high = "black",
      name = "q value\n(-log10)"
    ) +
    scale_size_continuous(
      range = c(1.2, 6),
      trans = "log10",
      name = "Abundance\n(total RPM)"
    ) +
    labs(
      title = "Microbial taxa associated with ARG abundance in mangrove sediments",
      x = "ARG group",
      y = paste0(str_to_title(target_rank), " taxa")
    ) +
    theme_nature(base_size = 8) +
    theme(
      legend.position = "bottom"
    )
}

p_a

# ----------------------------
# 10. Optional scatter panels for top correlated pairs
# ----------------------------

if (make_scatter_panels) {
  top_pairs <- cor_df %>%
    filter(!is.na(correlation), !is.na(q_value)) %>%
    arrange(desc(abs(correlation)), q_value) %>%
    slice_head(n = n_scatter_pairs)
  
  scatter_df <- list()
  
  for (i in seq_len(nrow(top_pairs))) {
    tk <- top_pairs$taxon_key[i]
    ag <- as.character(top_pairs$arg_group[i])
    
    one_df <- tibble(
      sample_id = taxa_mat$sample_id,
      taxa_abundance = taxa_mat[[tk]],
      arg_abundance = arg_mat[[ag]]
    ) %>%
      mutate(
        pair_id = paste0(
          top_pairs$domain[i], ": ",
          top_pairs$taxon_plot_label[i],
          " vs ",
          ag
        ),
        domain = top_pairs$domain[i],
        correlation = top_pairs$correlation[i],
        q_value = top_pairs$q_value[i],
        n_used = top_pairs$n_used[i]
      )
    
    scatter_df[[i]] <- one_df
  }
  
  scatter_df <- bind_rows(scatter_df)
  
  label_df <- scatter_df %>%
    group_by(pair_id, domain, correlation, q_value, n_used) %>%
    summarise(
      x_pos = quantile(taxa_abundance + pseudo_count, 0.05, na.rm = TRUE),
      y_pos = quantile(arg_abundance + pseudo_count, 0.95, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    mutate(
      label = paste0(
        "r = ", round(correlation, 3),
        "\nq = ", scientific(q_value, digits = 2),
        "\nn = ", n_used
      )
    )
  
  p_scatter <- ggplot(
    scatter_df,
    aes(
      x = taxa_abundance + pseudo_count,
      y = arg_abundance + pseudo_count,
      color = domain
    )
  ) +
    geom_point(size = 1.6, alpha = 0.8) +
    geom_smooth(
      method = "lm",
      se = FALSE,
      linewidth = 0.45,
      linetype = "dashed",
      color = "black"
    ) +
    geom_text(
      data = label_df,
      aes(x = x_pos, y = y_pos, label = label),
      inherit.aes = FALSE,
      hjust = 0,
      vjust = 1,
      size = 3
    ) +
    facet_wrap(~ pair_id, scales = "free", nrow = 1) +
    scale_x_log10(labels = scientific_format()) +
    scale_y_log10(labels = scientific_format()) +
    scale_color_npg() +
    labs(
      title = "Representative taxon-ARG relationships",
      x = paste0(str_to_title(target_rank), " abundance + pseudo-count"),
      y = "ARG abundance + pseudo-count",
      color = "Domain"
    ) +
    theme_nature(base_size = 8) +
    theme(
      legend.position = "none"
    )
  
  p_scatter
}

# ----------------------------
# 11. Combined figure
# ----------------------------

if (make_scatter_panels && exists("p_scatter")) {
  final_fig <- p_a / p_scatter +
    plot_layout(heights = c(1.6, 1)) +
    plot_annotation(
      tag_levels = "a",
      theme = theme(
        plot.tag = element_text(face = "bold", size = 12)
      )
    )
} else {
  final_fig <- p_a +
    plot_annotation(
      tag_levels = "a",
      theme = theme(
        plot.tag = element_text(face = "bold", size = 12)
      )
    )
}

final_fig

# ----------------------------
# 12. Save figures
# ----------------------------

n_taxa_plot <- n_distinct(cor_df$taxon_plot_label)
n_arg_plot <- n_distinct(cor_df$arg_group)

if (panel_a_orientation == "horizontal") {
  fig_width_mm <- max(180, min(420, 8 * n_taxa_plot))
  fig_height_mm <- ifelse(make_scatter_panels, 150, 100)
} else {
  fig_width_mm <- max(150, 35 * n_arg_plot)
  fig_height_mm <- max(140, min(420, 5 * n_taxa_plot))
}

ggsave(
  filename = file.path(output_dir, paste0("microbe_ARG_correlation_", target_rank, ".pdf")),
  plot = final_fig,
  width = fig_width_mm,
  height = fig_height_mm,
  units = "mm",
  device = cairo_pdf
)

ggsave(
  filename = file.path(output_dir, paste0("microbe_ARG_correlation_", target_rank, ".png")),
  plot = final_fig,
  width = fig_width_mm,
  height = fig_height_mm,
  units = "mm",
  dpi = 600
)

message("[DONE] Results written to: ", output_dir)